name: Generate Missing Cheatsheet

on:
  repository_dispatch:
    types: [generate-missing-cheatsheet]

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Find missing cheatsheets
        id: find_missing
        run: |
          cheatsheets=$(awk '/const cheatsheets = \[/, /\]/{ print }' core.js \
            | grep -v '//NEW-CHEATSHEET' \
            | grep -o '"[^"]\+"' \
            | sed 's/"//g')

          missing=""
          for sheet in $cheatsheets; do
            file="cheatsheets/${sheet}.html"
            if [ ! -f "$file" ]; then
              missing=$sheet
              break
            fi
          done

          echo "missing=$missing" >> $GITHUB_OUTPUT

      - name: Call OpenAI API to generate HTML
        id: generate_html
        run: |
          topic=${{ steps.find_missing.outputs.missing }}
          prompt="Generate a dense, printable, Tailwind-styled HTML cheat sheet for: $topic"

          html=$(curl https://api.openai.com/v1/chat/completions \
            -s \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-4",
              "messages": [{"role": "user", "content": "'$prompt'"}],
              "temperature": 0.7
            }' | jq -r '.choices[0].message.content')

          echo "$html" > cheatsheets/$topic.html

      - name: Create and push PR branch
        run: |
          branch="feature/add-${{ steps.find_missing.outputs.missing }}"
          git checkout -b $branch
          git add cheatsheets/${{ steps.find_missing.outputs.missing }}.html
          git commit -m "Add cheat sheet: ${{ steps.find_missing.outputs.missing }}"
          git push origin $branch

          gh pr create --base main --head $branch \
            --title "Add cheat sheet: ${{ steps.find_missing.outputs.missing }}" \
            --body "This PR adds the generated cheat sheet for ${{ steps.find_missing.outputs.missing }}."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
